language: node_js
node_js:
  - "7"
  - "6"
  - "5"
  - "4"

install:
  - cd $TRAVIS_BUILD_DIR && npm install

script:
  - cd $TRAVIS_BUILD_DIR && npm test

cache:
  directories:
    - "node_modules"

sudo: false
